### PR TITLE
Added check for email verification as per #267

### PR DESCRIPTION
**Pull request by realmayus**

### CODE REVIEW

**Comment by realmayus** [comment]
https://github.com/corona-school/project-user/issues/267

**Review by lsc0498 — CHANGES_REQUESTED** [review]
Where is this error used? With this I still can successfully enter the queue with an unverified address.

**Comment by realmayus** [comment]
> Where is this error used? With this I still can successfully enter the queue with an unverified address.

It's used in the screening front end, see this PR: https://github.com/corona-school/web-screening-app/pull/10

**Comment by realmayus** [comment]
> I mean, where is it used in the code of the screening backend? I can't find where it is effectively thrown when an email address turns out to be unverified. Maybe there was something missing when committing?

Oops! You were right, i forgot to push some of the files, thanks for the heads up.

**Review by lsc0498 — APPROVED** [review]
Great, thanks a lot!🎉

**Pull request merged**
